import{a as B,S as P,i as n}from"./assets/vendor-CyQxvrJ3.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const $="54229410-94c77c5f0b522302148c51193",E="https://pixabay.com/api/",p=async(r,e=1)=>(await B.get(E,{params:{key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data,y=document.querySelector(".gallery"),g=document.querySelector(".loader"),R=new P(".gallery a"),h=document.querySelector(".load-btn"),f=r=>{const e=r.map(({webformatURL:i,largeImageURL:s,tags:t,likes:o,views:a,comments:q,downloads:w})=>`<li class="gallery-item"><a href="${s}">
        <div class="card">
                <img class="card-image" src="${i}" alt="${t}" width="370" height="334"/>
            <div class="card-body">
            <span class="card-body-title">
                <p class="card-subtitle">likes: ${o}</p>
                <p class="card-subtitle">views: ${a}</p>
                <p class="card-subtitle">comments: ${q}</p>
                <p class="card-subtitle">downloads: ${w}</p>
            </span>
            </div>
        </div>
        </a>
        </li>`).join("");y.insertAdjacentHTML("beforeend",e),R.refresh()},M=()=>{y.innerHTML=""},b=()=>{g.classList.add("hidden")},L=()=>{g.classList.remove("hidden")},v=()=>{h.classList.remove("hidden")},c=()=>{h.classList.add("hidden")},O=document.querySelector(".form"),u=document.querySelector("#input"),A=document.querySelector(".load-btn");let d=1,m="";const l=15;O.addEventListener("submit",async r=>{r.preventDefault();const e=u.value.trim();if(!e){n.error({position:"topRight",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!💔"});return}m=e,d=1,c(),L(),M();try{const s=(await p(m,d,l)).hits;s.length===0?(setTimeout(()=>{n.error({position:"topRight",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!💔"})},1e3),u.value="",c()):setTimeout(()=>{f(s),u.value="",S(s,l),s.length===l?v():c()},1e3)}catch(i){n.error({position:"topRight",message:"Sorry💔"}),console.error(i)}finally{b()}});function S(r,e){r.length<e?(n.info({position:"topRight",message:"We're sorry, but you've reached the end of search results.💔"}),c()):v()}A.addEventListener("click",async()=>{c(),L(),d+=1;try{const e=p(m,d,l).hits;f(e),I(),S(e,l)}catch(r){n.error({position:"topRight",message:"Sorry💔"}),console.error(r)}finally{b()}});function I(){const r=document.querySelector(".gallery li");if(r){const{height:e}=r.getBoundingClientRect();requestAnimationFrame(()=>{window.scrollBy({top:e*2,behavior:"smooth"})})}}
//# sourceMappingURL=index.js.map
