import{a as w,S as B,i as c}from"./assets/vendor-CyQxvrJ3.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const P="54229410-94c77c5f0b522302148c51193",$="https://pixabay.com/api/",m=async(r,t=1)=>(await w.get($,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data,p=document.querySelector(".gallery"),h=document.querySelector(".loader"),E=new B(".gallery a"),g=document.querySelector(".load-btn"),y=r=>{const t=r.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:n,comments:S,downloads:q})=>`<a href="${i}">
        <div class="card">
                <img class="card-image" src="${s}" alt="${e}" width="370" height="334"/>
            <div class="card-body">
            <span class="card-body-title">
                <p class="card-subtitle">likes: ${o}</p>
                <p class="card-subtitle">views: ${n}</p>
                <p class="card-subtitle">comments: ${S}</p>
                <p class="card-subtitle">downloads: ${q}</p>
            </span>
            </div>
        </div>
        </a>`).join("");p.insertAdjacentHTML("beforeend",t),E.refresh()},M=()=>{p.innerHTML=""},f=()=>{h.classList.add("hidden")},L=()=>{h.classList.remove("hidden")},b=()=>{g.classList.remove("hidden")},a=()=>{g.classList.add("hidden")},O=document.querySelector(".form"),d=document.querySelector("#input"),R=document.querySelector(".load-btn");let l=1,u="";const v=15;O.addEventListener("submit",r=>{r.preventDefault();const t=d.value.trim();if(!t){c.error({position:"topRight",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!💔"});return}u=t,l=1,a(),L(),M(),m(u,l).then(s=>{console.log(s);const i=s.hits;i.length===0?(setTimeout(()=>{c.error({position:"topRight",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!💔"})},1e3),d.value="",a()):setTimeout(()=>{y(i),d.value="",i.length===v?b():a()},1e3)}).catch(s=>{c.error({position:"topRight",message:"Sorry💔"}),console.error(s)}).finally(()=>{f()})});function A(){const r=document.querySelector(".gallery li");if(r){const{height:t}=r.getBoundingClientRect();requestAnimationFrame(()=>{window.scrollBy({top:t*2,behavior:"smooth"})})}}R.addEventListener("click",()=>{a(),L(),l+=1,m(u,l).then(r=>{const t=r.hits;y(t),A(),t.length<v?(c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results.💔"}),a()):b()}).catch(r=>console.error(r)).finally(()=>{f()})});
//# sourceMappingURL=index.js.map
